apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: default
resources:
  - ../../base
patches:
  - path: image-patch.yaml
    target:
      kind: Deployment
      name: welcome-app